// Dados de exemplo para demonstração no editor de tema

export const demoAnnouncements = [
  {
    id: 'demo-1',
    text: 'Frete Grátis Sul e Sudeste a partir de R$299',
    background_color: '#EC4899',
    text_color: '#FFFFFF',
    icon: '🚚',
    link_url: null,
    is_active: true,
    order_index: 0,
  },
  {
    id: 'demo-2',
    text: 'Novidades chegando toda semana! Fique por dentro',
    background_color: '#3B82F6',
    text_color: '#FFFFFF',
    icon: '🎉',
    link_url: null,
    is_active: true,
    order_index: 1,
  },
]

export const demoBanners = [
  {
    id: 'demo-banner-1',
    title: 'Promoção Especial',
    subtitle: 'Até 50% OFF em toda a loja',
    image_url: '/demo-images/banners/banner-1.jpg',
    image_url_mobile: '/demo-images/banners/banner-1-mobile.jpg',
    link_url: null,
    is_active: true,
    order_index: 0,
  },
]

export const demoCategories = [
  {
    id: 'demo-cat-1',
    name: 'Destaques',
    description: 'Produtos em destaque',
    image_url: null,
    order_index: 0,
    is_active: true,
  },
  {
    id: 'demo-cat-2',
    name: 'Novidades',
    description: 'Lançamentos',
    image_url: null,
    order_index: 1,
    is_active: true,
  },
]

export const demoProducts = [
  {
    id: 'demo-prod-1',
    name: 'Produto de exemplo',
    description: 'Descrição do produto de exemplo para demonstração',
    price: 96.00,
    original_price: 120.00,
    image_url: '/demo-images/products/produto-1.jpg',
    stock_quantity: 10,
    is_unlimited_stock: false,
    is_active: true,
    is_featured: true,
    category_id: 'demo-cat-1',
    order_index: 0,
    discount_percentage: 20,
  },
  {
    id: 'demo-prod-2',
    name: 'Produto de exemplo',
    description: 'Descrição do produto de exemplo para demonstração',
    price: 122.00,
    original_price: null,
    image_url: '/demo-images/products/produto-2.jpg',
    stock_quantity: 15,
    is_unlimited_stock: false,
    is_active: true,
    is_featured: true,
    category_id: 'demo-cat-1',
    order_index: 1,
    discount_percentage: null,
  },
  {
    id: 'demo-prod-3',
    name: 'Produto de exemplo',
    description: 'Descrição do produto de exemplo para demonstração',
    price: 320.00,
    original_price: null,
    image_url: '/demo-images/products/produto-3.jpg',
    stock_quantity: 8,
    is_unlimited_stock: false,
    is_active: true,
    is_featured: true,
    category_id: 'demo-cat-1',
    order_index: 2,
    discount_percentage: null,
  },
  {
    id: 'demo-prod-4',
    name: 'Produto de exemplo',
    description: 'Descrição do produto de exemplo para demonstração',
    price: 420.00,
    original_price: null,
    image_url: '/demo-images/products/produto-4.jpg',
    stock_quantity: 12,
    is_unlimited_stock: false,
    is_active: true,
    is_featured: true,
    category_id: 'demo-cat-1',
    order_index: 3,
    discount_percentage: null,
  },
  {
    id: 'demo-prod-5',
    name: 'Produto de exemplo',
    description: 'Descrição do produto de exemplo para demonstração',
    price: 89.90,
    original_price: 149.90,
    image_url: '/demo-images/products/produto-5.jpg',
    stock_quantity: 20,
    is_unlimited_stock: false,
    is_active: true,
    is_featured: false,
    category_id: 'demo-cat-2',
    order_index: 4,
    discount_percentage: 40,
  },
  {
    id: 'demo-prod-6',
    name: 'Produto de exemplo',
    description: 'Descrição do produto de exemplo para demonstração',
    price: 199.90,
    original_price: null,
    image_url: '/demo-images/products/produto-6.jpg',
    stock_quantity: 5,
    is_unlimited_stock: false,
    is_active: true,
    is_featured: false,
    category_id: 'demo-cat-2',
    order_index: 5,
    discount_percentage: null,
  },
  {
    id: 'demo-prod-7',
    name: 'Produto de exemplo',
    description: 'Descrição do produto de exemplo para demonstração',
    price: 75.00,
    original_price: 100.00,
    image_url: '/demo-images/products/produto-7.jpg',
    stock_quantity: 18,
    is_unlimited_stock: false,
    is_active: true,
    is_featured: false,
    category_id: 'demo-cat-1',
    order_index: 6,
    discount_percentage: 25,
  },
  {
    id: 'demo-prod-8',
    name: 'Produto de exemplo',
    description: 'Descrição do produto de exemplo para demonstração',
    price: 159.90,
    original_price: null,
    image_url: '/demo-images/products/produto-8.jpg',
    stock_quantity: 7,
    is_unlimited_stock: false,
    is_active: true,
    is_featured: false,
    category_id: 'demo-cat-2',
    order_index: 7,
    discount_percentage: null,
  },
]

export const demoStore = {
  id: 'demo-store',
  name: 'Minha Loja',
  slug: 'minha-loja',
  primary_color: '#004DF0',
  logo_url: null,
}

export const demoSettings = {
  id: 'demo-settings',
  font_family: 'Inter',
  layout_style: 'default',
  show_address: false,
  address: null,
  about_text: 'Use este texto para compartilhar informações da sua loja, dar boas vindas aos clientes ou para dizer o quão incrível são os seus produtos.',
  opening_hours: null,
  custom_css: null,
  products_per_row: 2,
  products_per_row_mobile: 2,
}


